In [9]:
import numpy as np
import hashlib
import re

Name A: Vegard Vaeng Bernhardsen

Name B: None 

In [10]:
#Four (4) 'relevant' TDT4305 sentences

Sentence_1 = "The Big Data platform for students is Blackboard"
Sentence_2 = "Questions on MinHash project by NTNU students is on Piazza"
Sentence_3 = "NTNU Big Data platform are Blackboard and Piazza"
Sentence_4 = "The project data for students are on Blackboard not Piazza"

In [11]:
words = ["big", "blackboard", "data", "platform", "students", "questions", "minhash", "project", "ntnu", "piazza"]

# Organize the array in alphabetical order
sorted_words = sorted(words)

print(sorted_words)

unique_words = sorted_words # Enter the unique words list here

# ['big', 'blackboard', 'data', 'minhash', 'ntnu', 'piazza', 'platform', 'project', 'questions', 'students']


['big', 'blackboard', 'data', 'minhash', 'ntnu', 'piazza', 'platform', 'project', 'questions', 'students']


In [12]:
# User input

print(f"Format: ['word', 'word', 'word' ...] & watch out for white spaces before comma")
user_input = str(sorted_words) # str(input("Enter your created list of unique words: ")) 
# Changed to str(sorted_words) for testing purposes

f = open("encrypted_dictionary.txt", "r")
encrypted_words = f.read()


# Hash the user input
hashed_user_input = hashlib.sha256(user_input.encode()).hexdigest()

# Compare with the stored hash
if hashed_user_input == encrypted_words:
    print("Correct! Your dictionary matched!")
else:
    print("Incorrect! Try again.")

Format: ['word', 'word', 'word' ...] & watch out for white spaces before comma
Correct! Your dictionary matched!


In [13]:
# Lowercase sentences for uniform processing
sentences = [Sentence_1.lower(), Sentence_2.lower(), Sentence_3.lower(), Sentence_4.lower()]

# Initialize the Input Matrix
input_matrix = np.zeros((len(unique_words), len(sentences)), dtype=int)

# Populate the Input Matrix
for i, word in enumerate(unique_words):
    for j, sentence in enumerate(sentences):
        if word in sentence:
            input_matrix[i, j] = 1

print("Input Matrix:")
print(input_matrix)


Input Matrix:
[[1 0 1 0]
 [1 0 1 1]
 [1 0 1 1]
 [0 1 0 0]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 1 0]
 [0 1 0 1]
 [0 1 0 0]
 [1 1 0 1]]


In [14]:
n = len(unique_words)

hash_1 = []
for i in range(1, n + 1):
    hash_1.append( ( ( (i + 3) % 10 ) + 1) )
    
hash_2 = []
for i in range(1, n + 1):
    hash_2.append( ( ( (7 * i + 1) % 10 ) + 1) )

hash_3 = []
for i in range(1, n + 1):
    hash_3.append( ( ( (7 * i + 2) % 10 ) + 1) )

hash_list = [hash_1, hash_2, hash_3]

print("hash_list:", hash_list)


hash_list: [[5, 6, 7, 8, 9, 10, 1, 2, 3, 4], [9, 6, 3, 10, 7, 4, 1, 8, 5, 2], [10, 7, 4, 1, 8, 5, 2, 9, 6, 3]]


In [15]:

# Initialize the Signature Matrix with infinite values
Sig_M = np.full((3, len(sentences)), np.inf)

# Compute the MinHash Signature Matrix
for i in range(Sig_M.shape[0]):
    for j in range(Sig_M.shape[1]):
        for k in range(len(unique_words)):
            if input_matrix[k, j] == 1:
                Sig_M[i, j] = min(Sig_M[i, j], hash_list[i][k])

print("MinHash Signature Matrix:")
print(Sig_M.astype(int))


MinHash Signature Matrix:
[[1 2 1 2]
 [1 2 1 2]
 [2 1 2 3]]


In [16]:
# Function to calculate Jaccard similarity between two columns in the signature matrix
def calculate_jaccard(Sig_M, col1, col2):
    match = np.sum(Sig_M[:, col1] == Sig_M[:, col2])
    return match / Sig_M.shape[0]

# Display Jaccard Similarity for each sentence pair
for i in range(Sig_M.shape[1]):
    for j in range(i + 1, Sig_M.shape[1]):
        similarity = calculate_jaccard(Sig_M, i, j)
        print(f"Jaccard Similarity between Sentence {i + 1} and Sentence {j + 1}: {similarity:.3f}")


Jaccard Similarity between Sentence 1 and Sentence 2: 0.000
Jaccard Similarity between Sentence 1 and Sentence 3: 1.000
Jaccard Similarity between Sentence 1 and Sentence 4: 0.000
Jaccard Similarity between Sentence 2 and Sentence 3: 0.000
Jaccard Similarity between Sentence 2 and Sentence 4: 0.667
Jaccard Similarity between Sentence 3 and Sentence 4: 0.000
